<?php

/**
 * @file
 * Module file for the Better field descriptions module.
 *
 * The module hooks into forms and adds a better description to fields.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Xss;

/**
 * Implements hook_help().
 */
function better_field_descriptions_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.better_field_descriptions') {
    return t('Allows users with certain roles to add themeable descriptions to fields in forms. The module consists of two parts. One is configuring which fields in which content types that should be configured to have a better description. The other part is editing the descriptions themselves.');
  }
}

/**
 * Implements hook_theme().
 */
function better_field_descriptions_theme($existing, $type, $theme, $path) {

  $bfd = \Drupal::config('better_field_descriptions.settings')->get('better_field_descriptions');

  // Find the theme template or use default if not configured.
  if (isset($bfd['template']) == FALSE || empty($bfd['template'])) {
    $template_file = 'better-field-descriptions-fieldset';
  }
  else {
    $template_file = $bfd['template'];
  }

  // Find the theme template URI .
  if ($template_file == 'better-field-descriptions-fieldset') {
    $template_uri = drupal_get_path('module', 'better_field_descriptions') . '/templates';
  }
  else {
    $template_uri = $bfd['template_uri'];
    $template_uri = str_replace('/' . $template_file . '.html.twig', '', $template_uri);
  }

  return array(
    'better_field_descriptions' => array(
      'variables' => array('label' => NULL, 'description' => NULL),
      'template' => $template_file,
      'path' => $template_uri,
    ),
  );
}

/**
 * Implements hook_form_alter().
 *
 * Future improvements: add a theming function for the #suffix content. Users
 * could then add their own template and select template from the settings page.
 */
function better_field_descriptions_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $bundle = $form_state->getFormObject()->getEntity()->getType();

  // Get better descriptions.
  $bfd = \Drupal::config('better_field_descriptions.settings')->get('better_field_descriptions');

  // Only add descriptions if the bundle field is configured with one.
  if (isset($bfd[$bundle])) {
    $form['#attached']['library'][] = 'core/drupal.form';
    $form['#attached']['library'][] = 'core/drupal.collapse';

    // Default label.
    $default_label = Xss::filter($bfd['default_label']);

    // Available positions.
    $positions = array(0 => '#prefix', 1 => '#suffix', 2 => 'between');

    // Adding description to field if configured.
    foreach ($bfd[$bundle] as $field => $data) {
      if (isset($form[$field]) && !empty($data['description'])) {

        // Set position if configured or set default to #suffix.
        $position = isset($data['position']) ? $positions[$data['position']] : '#suffix';

        // The description as configured.
        $description = $data['description'];

        switch ($position) {

          case '#suffix':
          case '#prefix':

            $label = empty($data['label'])
              ? $default_label
              : $data['label'];
            break;

          case 'between':

            $label = (empty($data['label']) && !empty($form[$field][LANGUAGE_NONE]['#title']))
              ? $form[$field][LANGUAGE_NONE]['#title']
              : $data['label'];

            $form[$field][LANGUAGE_NONE]['#title_display'] = 'invisible';
            $form[$field][LANGUAGE_NONE][0]['#title_display'] = 'invisible';
            $position = '#prefix';
            break;
        }

        $output = [
          '#theme' => 'better_field_descriptions',
          '#label' => Xss::filter($label),
          '#description' => Xss::filter($description),
        ];
        $output = drupal_render($output);

        // Adding descriptions to form.
        // Special case for pseudo fields.
        if ($field == 'title') {
          $form[$field]['#prefix'] = '';
          $form[$field]['#suffix'] = '';
          $form[$field][$position] = $output;
        }
        else {
          $form[$field][LANGUAGE_NONE]['#prefix'] = '';
          $form[$field][LANGUAGE_NONE]['#suffix'] = '';
          $form[$field][LANGUAGE_NONE][$position] = $output;
        }
      }
    }
  }
}
